# Base containerfile to base agent-sandbox containers off of
FROM fedora:43

RUN <<EOF
  set -e
  # Base tooling
  dnf install -y which python3-pip
  # Version control
  dnf install -y git gh
  # Build tools and linters
  dnf install -y clang shellcheck
  # Search, text processing, and utilities
  dnf install -y ripgrep jq yq xxd fd-find tokei cloc bc vim
  # Conversion/parsing of PDF/html and similar document types
  dnf install -y poppler-utils pandoc
  # Networking
  dnf install -y socat netcat
  # Clean up and remove cache to slim down image
  dnf clean all
  rm -rf /var/cache/dnf
EOF

# Install more PDF parsing tools
RUN pip install pymupdf pdfplumber

USER ${USERNAME}
# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    --default-toolchain stable \
    --profile default \
    --component rust-analyzer,miri,rustfmt
ENV PATH="${USER_HOME}/.cargo/bin:${PATH}"

# Install cargo-binstall. Allows installing other Rust tools way faster
RUN curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

# Install cargo-shear for checking unused dependencies
RUN cargo binstall cargo-shear
